Use CustomerShoppingDB

--Q1. Total revenue generated by Male vs Female customers

SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM CustomerShoppingBehavior
GROUP BY gender
ORDER BY total_revenue DESC;

--Q2. Customers who received a discount but spent more than the average purchase amount

SELECT
    customer_id,
    gender,
    item_purchased,
    purchase_amount,
    discount_applied
FROM CustomerShoppingBehavior
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM CustomerShoppingBehavior
  )
ORDER BY purchase_amount DESC;

--Q3. Top 5 products with the highest average review rating

SELECT TOP 5
    item_purchased,
    AVG(review_rating) AS average_review_rating
FROM CustomerShoppingBehavior
GROUP BY item_purchased
ORDER BY average_review_rating DESC;

--Q4. Compare average purchase amount between Standard and Express Shipping

SELECT
    shipping_type,
    AVG(purchase_amount) AS average_purchase_amount
FROM CustomerShoppingBehavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY average_purchase_amount DESC;

--Q5. Do subscribed customers spend more?

--Compare average spend and total revenue.

SELECT
    subscription_status,
    AVG(purchase_amount) AS average_spend,
    SUM(purchase_amount) AS total_revenue,
    COUNT(*) AS total_customers
FROM CustomerShoppingBehavior
GROUP BY subscription_status
ORDER BY average_spend DESC;

--Q6. Top 5 products with the highest percentage of purchases with discounts

SELECT TOP 5
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE
        WHEN discount_applied = 'Yes' THEN 1
        ELSE 0
    END) AS discounted_purchases,
    CAST(
        SUM(CASE
            WHEN discount_applied = 'Yes' THEN 1.0
            ELSE 0
        END) * 100.0 / COUNT(*)
        AS DECIMAL(5,2)
    ) AS discount_percentage
FROM CustomerShoppingBehavior
GROUP BY item_purchased
ORDER BY discount_percentage DESC;

--Q7. Compare New, Returning and Loyal customers

SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM
(
    SELECT
        customer_id,
        CASE
            WHEN previous_purchases BETWEEN 0 AND 5 THEN 'New'
            WHEN previous_purchases BETWEEN 6 AND 20 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM CustomerShoppingBehavior
) AS segments
GROUP BY customer_segment
ORDER BY number_of_customers DESC;

--Q8. Top 3 most purchased products within each category

--This is a good use of SQL window functions.

WITH ProductCounts AS
(
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM CustomerShoppingBehavior
    GROUP BY
        category,
        item_purchased
),
RankedProducts AS
(
    SELECT
        category,
        item_purchased,
        purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS product_rank
    FROM ProductCounts
)
SELECT
    category,
    item_purchased,
    purchase_count,
    product_rank
FROM RankedProducts
WHERE product_rank <= 3
ORDER BY category, product_rank;

--Q9. Are repeat buyers (>5 previous purchases) more likely to subscribe?

SELECT
    CASE
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,

    COUNT(*) AS total_customers,

    SUM(CASE
        WHEN subscription_status = 'Yes' THEN 1
        ELSE 0
    END) AS subscribed_customers,

    CAST(
        SUM(CASE
            WHEN subscription_status = 'Yes' THEN 1.0
            ELSE 0
        END) * 100.0 / COUNT(*)
        AS DECIMAL(5,2)
    ) AS subscription_rate
FROM CustomerShoppingBehavior
GROUP BY
    CASE
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END;

   -- Q10. Revenue contribution of each age group

   SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue,

    CAST(
        SUM(purchase_amount) * 100.0 /
        (SELECT SUM(purchase_amount)
         FROM CustomerShoppingBehavior)
        AS DECIMAL(5,2)
    ) AS revenue_percentage

FROM CustomerShoppingBehavior
GROUP BY age_group
ORDER BY total_revenue DESC;